--Ngành--
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'' where ChuyenNganh = N''
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'' where ChuyenNganh = N''
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Cấp thoát nước' where ChuyenNganh = N'Cấp thoát nước'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Cơ giới hóa' where ChuyenNganh = N'Cơ giới hóa'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Cơ giới hóa xây dựng' where ChuyenNganh = N'Cơ giới hóa xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Cơ sở hạ tầng giao thông' where ChuyenNganh = N'Cơ sở hạ tầng giao thông'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Công nghệ và Quản lý Môi trường' where ChuyenNganh = N'Công nghệ & Quản lý Môi trường'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Công nghệ thông tin' where ChuyenNganh = N'Công nghệ thông tin'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Hệ thống kỹ thuật trong công trình' where ChuyenNganh = N'Hệ thống kỹ thuật trong công trình'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Hệ thống kỹ thuật trong công trình' where ChuyenNganh = N'Hệ thống Kỹ thuật trong công trình'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kiến trúc' where ChuyenNganh = N'Kiến trúc'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kiến trúc' where ChuyenNganh = N'Kiến trúc'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kinh tế và Quản lý Bất động sản' where ChuyenNganh = N'Kinh tê & QL BDS'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kinh tế và Quản lý Đô thị' where ChuyenNganh = N'Kinh tế & Quản lý đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kinh tế và Quản lý Bất động sản' where ChuyenNganh = N'Kinh tế và Quản lý Bất động sản'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kinh tế và Quản lý Đô thị' where ChuyenNganh = N'Kinh tế và Quản lý đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kinh tế Xây dựng' where ChuyenNganh = N'Kinh tế Xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kinh tế Xây dựng' where ChuyenNganh = N'Kinh tế xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'KV' where ChuyenNganh = N'KV'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kỹ thuật Công trình thủy' where ChuyenNganh = N'Kỹ thuật công trình thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kỹ thuật Đô thị' where ChuyenNganh = N'Kỹ thuật đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kỹ thuật Đô thị' where ChuyenNganh = N'Kỹ thuật đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kỹ thuật Trắc địa Xây dựng - Địa chính' where ChuyenNganh = N'Kỹ thuật trắc địa Xây dựng - Địa chính'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Kỹ thuật Trắc địa xây dựng - Địa chính' where ChuyenNganh = N'Kỹ thuật Trắc địa xây dựng - Địa chính'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Máy xây dựng' where ChuyenNganh = N'Máy xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Nội thất' where ChuyenNganh = N'Nội thất'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Quy hoạch vùng và đô thị' where ChuyenNganh = N'Quy hoạch vùng và đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Tin học Xây dựng' where ChuyenNganh = N'Tin học Xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Vật liệu Xây dựng' where ChuyenNganh = N'Vật liệu xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Cảng - Đường thủy' where ChuyenNganh = N'Xây dựng Cảng - Đường thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Cảng - Đường thủy' where ChuyenNganh = N'Xây dựng Cảng - Đường thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Cầu đường' where ChuyenNganh = N'Xây dựng Cầu đường'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Công trình biển - Dầu khí' where ChuyenNganh = N'Xây dựng Công trình biển - Dầu khí'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Công trình biển - Dầu khí' where ChuyenNganh = N'Xây dựng Công trình biển - Dầu khí'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Công trình ven biển' where ChuyenNganh = N'Xây dựng công trình ven biển'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Công trình ven biển' where ChuyenNganh = N'Xây dựng Công trình ven biển'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Dân dụng và Công nghiệp' where ChuyenNganh = N'Xây dựng Dân dụng & Công nghiệp'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Dân dụng và Công nghiệp' where ChuyenNganh = N'Xây dựng Dân dụng và Công nghiệp'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Thủy lợi - Thủy điện' where ChuyenNganh = N'Xây dựng Thủy lợi - Thủy điện'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set ChuyenNganh = N'Xây dựng Thủy lợi - Thủy điện' where ChuyenNganh = N'Xây dựng Thủy lợi - Thủy điện'

--Ngành bảng student
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'' where tenchnga = N''
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'' where tenchnga = N''
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Cấp thoát nước' where tenchnga = N'Cấp thoát nước'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Cơ giới hóa' where tenchnga = N'Cơ giới hóa'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Cơ giới hóa xây dựng' where tenchnga = N'Cơ giới hóa xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Cơ sở hạ tầng giao thông' where tenchnga = N'Cơ sở hạ tầng giao thông'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Công nghệ và Quản lý Môi trường' where tenchnga = N'Công nghệ & Quản lý Môi trường'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Công nghệ thông tin' where tenchnga = N'Công nghệ thông tin'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Hệ thống kỹ thuật trong công trình' where tenchnga = N'Hệ thống kỹ thuật trong công trình'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Hệ thống kỹ thuật trong công trình' where tenchnga = N'Hệ thống Kỹ thuật trong công trình'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kiến trúc' where tenchnga = N'Kiến trúc'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kiến trúc' where tenchnga = N'Kiến trúc'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kinh tế và Quản lý Bất động sản' where tenchnga = N'Kinh tê & QL BDS'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kinh tế và Quản lý Đô thị' where tenchnga = N'Kinh tế & Quản lý đô thị'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kinh tế và Quản lý Bất động sản' where tenchnga = N'Kinh tế và Quản lý Bất động sản'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kinh tế và Quản lý Đô thị' where tenchnga = N'Kinh tế và Quản lý đô thị'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kinh tế Xây dựng' where tenchnga = N'Kinh tế Xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kinh tế Xây dựng' where tenchnga = N'Kinh tế xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'KV' where tenchnga = N'KV'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kỹ thuật Công trình thủy' where tenchnga = N'Kỹ thuật công trình thủy'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kỹ thuật Đô thị' where tenchnga = N'Kỹ thuật đô thị'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kỹ thuật Đô thị' where tenchnga = N'Kỹ thuật đô thị'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kỹ thuật Trắc địa Xây dựng - Địa chính' where tenchnga = N'Kỹ thuật trắc địa Xây dựng - Địa chính'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Kỹ thuật Trắc địa xây dựng - Địa chính' where tenchnga = N'Kỹ thuật Trắc địa xây dựng - Địa chính'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Máy xây dựng' where tenchnga = N'Máy xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Nội thất' where tenchnga = N'Nội thất'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Quy hoạch vùng và đô thị' where tenchnga = N'Quy hoạch vùng và đô thị'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Tin học Xây dựng' where tenchnga = N'Tin học Xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Vật liệu Xây dựng' where tenchnga = N'Vật liệu xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Cảng - Đường thủy' where tenchnga = N'Xây dựng Cảng - Đường thủy'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Cảng - Đường thủy' where tenchnga = N'Xây dựng Cảng - Đường thủy'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Cầu đường' where tenchnga = N'Xây dựng Cầu đường'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Công trình biển - Dầu khí' where tenchnga = N'Xây dựng Công trình biển - Dầu khí'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Công trình biển - Dầu khí' where tenchnga = N'Xây dựng Công trình biển - Dầu khí'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Công trình ven biển' where tenchnga = N'Xây dựng công trình ven biển'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Công trình ven biển' where tenchnga = N'Xây dựng Công trình ven biển'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Dân dụng và Công nghiệp' where tenchnga = N'Xây dựng Dân dụng & Công nghiệp'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Dân dụng và Công nghiệp' where tenchnga = N'Xây dựng Dân dụng và Công nghiệp'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Thủy lợi - Thủy điện' where tenchnga = N'Xây dựng Thủy lợi - Thủy điện'
update AS_Edu_Survey_Undergraduate_Student set tenchnga = N'Xây dựng Thủy lợi - Thủy điện' where tenchnga = N'Xây dựng Thủy lợi - Thủy điện'

--Chuyên ngành--
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'' where Nganh = N''
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cảng - đường thủy' where Nganh = N'Cảng - đường thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cấp thoát nước' where Nganh = N'Cấp thoát nước'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cơ giới hóa xây dựng' where Nganh = N'Cơ giới hoá xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cơ giới hóa xây dựng' where Nganh = N'Cơ giới hóa xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cơ giới hóa xây dựng' where Nganh = N'Cơ giới hóa XD'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cơ giới hóa xây dựng' where Nganh = N'Cơ giới hoỏ xõy dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Cơ sở hạ tầng giao thông' where Nganh = N'Cơ sở hạ tầng giao thông'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Công nghệ Kỹ thuật Môi trường' where Nganh = N'Công nghệ Kỹ thuật Môi trường'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Công nghệ kỹ thuật Vật liệu xây dựng' where Nganh = N'Công nghệ Kỹ thuật Vật liệu xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Công nghệ thông tin' where Nganh = N'Công nghệ thông tin'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Công nghệ và Quản lý môi trường' where Nganh = N'Công nghệ và Quản lý môi trường'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Hệ thống kỹ thuật trong công trình' where Nganh = N'Hệ thống kỹ thuật trong công trình'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kiến trúc' where Nganh = N'Kiến trúc'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế Quản lý Bất động sản' where Nganh = N'Kinh tế quản lý bất động sản'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế và Quản lý Bất động sản' where Nganh = N'Kinh tế và QLBĐS'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế và Quản lý Đô thị' where Nganh = N'Kinh tế và QLĐT'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế và Quản lý Bất động sản' where Nganh = N'Kinh tế và quản lý bất động sản'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế và Quản lý Đô thị' where Nganh = N'Kinh tế và Quản lý đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế và Quản lý Đô thị' where Nganh = N'Kinh tế và quản lý đụ thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế Xây dựng' where Nganh = N'Kinh tế Xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kinh tế Xây dựng' where Nganh = N'Kinh tế Xõy dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'KV' where Nganh = N'KV'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Cấp thoát nước' where Nganh = N'Kỹ thuật Cấp thoát nước'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Cơ khí' where Nganh = N'Kỹ thuật cơ khí'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Ký thuật Cơ khí (Chuyên ngành: Cơ giới hóa xây dựng)' where Nganh = N'Kỹ thuật Cơ khí (Chuyên ngành: Cơ giới hóa xây dựng)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Cơ khí (Chuyên ngành: Máy xây dựng)' where Nganh = N'Kỹ thuật Cơ khí (Chuyên ngành: Máy xây dựng)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Công trình biển' where Nganh = N'Kỹ thuật Công trình biển'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình Biển - Dầu khí)' where Nganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình Biển - Dầu khí)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình ven biển)' where Nganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình ven biển)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình thủy' where Nganh = N'kỹ thuật công trình thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng' where Nganh = N'Kỹ thuật công trình xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Hệ thống Kỹ thuật trong công trình)' where Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Hệ thống Kỹ thuật trong công trình)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Tin học Xây dựng)' where Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Tin học Xây dựng)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Thuỷ lợi - Thuỷ điện)' where Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Thuỷ lợi - Thuỷ điện)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Dân dụng và Công nghiệp)' where Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Dân dụng và Công nghiệp)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Dân dụng và Công nghiệp)' where Nganh = N'Kỹ thuật công trình xây dựng (CN: Xây dựng Dân dụng và Công nghiệp)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Cảng - Đường thủy)' where Nganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Cảng - Đường thuỷ)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật đô thị' where Nganh = N'kỹ thuật đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Trắc địa - Bản đồ' where Nganh = N'Kỹ thuật Trắc địa - Bản đồ'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật Trắc địa xây dựng - địa chính' where Nganh = N'Kỹ thuật Trắc địa xây dựng - địa chính'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật xây dựng' where Nganh = N'Kỹ thuật xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật xây dựng Công trình biển' where Nganh = N'Kỹ thuật xây dựng Công trình biển'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật xây dựng Công trình Giao thông' where Nganh = N'Kỹ thuật xây dựng Công trình Giao thông'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Kỹ thuật xây dựng Công trình Giao thông (Chuyên ngành: Xây dựng Cầu đường)' where Nganh = N'Kỹ thuật xây dựng Công trình Giao thông (Chuyên ngành: Xây dựng Cầu đường)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Máy xây dựng' where Nganh = N'Máy xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Máy xây dựng' where Nganh = N'Mỏy xõy dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Nội thất' where Nganh = N'Nội thất'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Quản lý Xây dựng' where Nganh = N'Quản lý Xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý Bất động sản)' where Nganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý Bất động sản)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý đô thị)' where Nganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý đô thị)'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Quy hoạch vùng và đô thị' where Nganh = N'Quy hoạch vùng và đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Quy hoạch vùng và đô thị' where Nganh = N'Quy hoạch vùng và đô thị'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Thủy lợi' where Nganh = N'Thủy lợi'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Tin học' where Nganh = N'Tin học'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Tin học xây dựng' where Nganh = N'Tin học xây dựng'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Cảng - Đường thủy' where Nganh = N'Xây dựng cảng - đường thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Cầu đường' where Nganh = N'Xây dựng cầu đường'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Công trình biển - Dầu khí' where Nganh = N'Xây dựng công trình biển - dầu khí'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Công trình ven biển' where Nganh = N'Xây dựng công trình ven biển'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Dân dụng và Công nghiệp' where Nganh = N'Xây dựng dân dụng và công nghiệp'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Thủy lợi - Thủy điện' where Nganh = N'Xây dựng thủy lợi - thủy điện'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Cảng - Đường thủy' where Nganh = N'Xõy dựng Cảng - Đường thủy'
update AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien set Nganh = N'Xây dựng Cầu đường' where Nganh = N'Xõy dựng cầu đường'

--ngành bảng student--
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'' where tennganh = N''
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cảng - đường thủy' where tennganh = N'Cảng - đường thủy'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cấp thoát nước' where tennganh = N'Cấp thoát nước'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cơ giới hóa xây dựng' where tennganh = N'Cơ giới hoá xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cơ giới hóa xây dựng' where tennganh = N'Cơ giới hóa xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cơ giới hóa xây dựng' where tennganh = N'Cơ giới hóa XD'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cơ giới hóa xây dựng' where tennganh = N'Cơ giới hoỏ xõy dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Cơ sở hạ tầng giao thông' where tennganh = N'Cơ sở hạ tầng giao thông'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Công nghệ Kỹ thuật Môi trường' where tennganh = N'Công nghệ Kỹ thuật Môi trường'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Công nghệ kỹ thuật Vật liệu xây dựng' where tennganh = N'Công nghệ Kỹ thuật Vật liệu xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Công nghệ thông tin' where tennganh = N'Công nghệ thông tin'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Công nghệ và Quản lý môi trường' where tennganh = N'Công nghệ và Quản lý môi trường'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Hệ thống kỹ thuật trong công trình' where tennganh = N'Hệ thống kỹ thuật trong công trình'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kiến trúc' where tennganh = N'Kiến trúc'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế Quản lý Bất động sản' where tennganh = N'Kinh tế quản lý bất động sản'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế và Quản lý Bất động sản' where tennganh = N'Kinh tế và QLBĐS'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế và Quản lý Đô thị' where tennganh = N'Kinh tế và QLĐT'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế và Quản lý Bất động sản' where tennganh = N'Kinh tế và quản lý bất động sản'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế và Quản lý Đô thị' where tennganh = N'Kinh tế và Quản lý đô thị'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế và Quản lý Đô thị' where tennganh = N'Kinh tế và quản lý đụ thị'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế Xây dựng' where tennganh = N'Kinh tế Xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kinh tế Xây dựng' where tennganh = N'Kinh tế Xõy dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'KV' where tennganh = N'KV'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Cấp thoát nước' where tennganh = N'Kỹ thuật Cấp thoát nước'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Cơ khí' where tennganh = N'Kỹ thuật cơ khí'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Ký thuật Cơ khí (Chuyên ngành: Cơ giới hóa xây dựng)' where tennganh = N'Kỹ thuật Cơ khí (Chuyên ngành: Cơ giới hóa xây dựng)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Cơ khí (Chuyên ngành: Máy xây dựng)' where tennganh = N'Kỹ thuật Cơ khí (Chuyên ngành: Máy xây dựng)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Công trình biển' where tennganh = N'Kỹ thuật Công trình biển'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình Biển - Dầu khí)' where tennganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình Biển - Dầu khí)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình ven biển)' where tennganh = N'Kỹ thuật Công trình biển (Chuyên ngành: Xây dựng Công trình ven biển)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình thủy' where tennganh = N'kỹ thuật công trình thủy'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng' where tennganh = N'Kỹ thuật công trình xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Hệ thống Kỹ thuật trong công trình)' where tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Hệ thống Kỹ thuật trong công trình)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Tin học Xây dựng)' where tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Tin học Xây dựng)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Thuỷ lợi - Thuỷ điện)' where tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Thuỷ lợi - Thuỷ điện)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Dân dụng và Công nghiệp)' where tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Dân dụng và Công nghiệp)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Dân dụng và Công nghiệp)' where tennganh = N'Kỹ thuật công trình xây dựng (CN: Xây dựng Dân dụng và Công nghiệp)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Cảng - Đường thủy)' where tennganh = N'Kỹ thuật công trình xây dựng (Chuyên ngành: Xây dựng Cảng - Đường thuỷ)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật đô thị' where tennganh = N'kỹ thuật đô thị'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Trắc địa - Bản đồ' where tennganh = N'Kỹ thuật Trắc địa - Bản đồ'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật Trắc địa xây dựng - địa chính' where tennganh = N'Kỹ thuật Trắc địa xây dựng - địa chính'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật xây dựng' where tennganh = N'Kỹ thuật xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật xây dựng Công trình biển' where tennganh = N'Kỹ thuật xây dựng Công trình biển'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật xây dựng Công trình Giao thông' where tennganh = N'Kỹ thuật xây dựng Công trình Giao thông'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Kỹ thuật xây dựng Công trình Giao thông (Chuyên ngành: Xây dựng Cầu đường)' where tennganh = N'Kỹ thuật xây dựng Công trình Giao thông (Chuyên ngành: Xây dựng Cầu đường)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Máy xây dựng' where tennganh = N'Máy xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Máy xây dựng' where tennganh = N'Mỏy xõy dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Nội thất' where tennganh = N'Nội thất'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Quản lý Xây dựng' where tennganh = N'Quản lý Xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý Bất động sản)' where tennganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý Bất động sản)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý đô thị)' where tennganh = N'Quản lý Xây dựng (Chuyên ngành: Kinh tế và Quản lý đô thị)'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Quy hoạch vùng và đô thị' where tennganh = N'Quy hoạch vùng và đô thị'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Quy hoạch vùng và đô thị' where tennganh = N'Quy hoạch vùng và đô thị'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Thủy lợi' where tennganh = N'Thủy lợi'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Tin học' where tennganh = N'Tin học'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Tin học xây dựng' where tennganh = N'Tin học xây dựng'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Cảng - Đường thủy' where tennganh = N'Xây dựng cảng - đường thủy'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Cầu đường' where tennganh = N'Xây dựng cầu đường'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Công trình biển - Dầu khí' where tennganh = N'Xây dựng công trình biển - dầu khí'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Công trình ven biển' where tennganh = N'Xây dựng công trình ven biển'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Dân dụng và Công nghiệp' where tennganh = N'Xây dựng dân dụng và công nghiệp'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Thủy lợi - Thủy điện' where tennganh = N'Xây dựng thủy lợi - thủy điện'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Cảng - Đường thủy' where tennganh = N'Xõy dựng Cảng - Đường thủy'
update AS_Edu_Survey_Undergraduate_Student set tennganh = N'Xây dựng Cầu đường' where tennganh = N'Xõy dựng cầu đường'
