//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Academy_Lecturer
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public string DepartmentCode { get; set; }
        public string DateOfBirth { get; set; }
        public string NameOrder { get; set; }
        public string Email { get; set; }
    }
}
