//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Academy_Lecturer_ClassRoom
    {
        public long ID { get; set; }
        public string ClassRoomCode { get; set; }
        public string LecturerCode { get; set; }
        public string NHHK { get; set; }
    }
}
