//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Academy_C_ClassRoom
    {
        public long ID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public string Code { get; set; }
        public string GroupCode { get; set; }
        public string ClassCode { get; set; }
        public Nullable<long> SubjectID { get; set; }
        public string SubjectCode { get; set; }
        public string ExamAttemptDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
