//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Academy_Class
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> FacultyID { get; set; }
        public string FacultyCode { get; set; }
        public Nullable<long> AcademicsID { get; set; }
        public string AcademicsCode { get; set; }
        public string SchoolYear { get; set; }
    }
}
