//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Edu_Survey_ReportTotal
    {
        public System.Guid ID { get; set; }
        public System.Guid SurveyRoundId { get; set; }
        public System.Guid TheSurveyId { get; set; }
        public string ClassRoomCode { get; set; }
        public string NHHK { get; set; }
        public string LecturerCode { get; set; }
        public string QuestionCode { get; set; }
        public string AnswerCode { get; set; }
        public Nullable<int> Total { get; set; }
        public string Content { get; set; }
        public string SubjectCode { get; set; }
        public string ClassRoom { get; set; }
    }
}
