//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Edu_Survey_CauTrucDe
    {
        public System.Guid ID { get; set; }
        public System.Guid DeThiID { get; set; }
        public System.Guid CauHoiID { get; set; }
        public int Order { get; set; }
    }
}
