//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien
    {
        public System.Guid ID { get; set; }
        public System.Guid BaiKhaoSatID { get; set; }
        public string StudentCode { get; set; }
        public string Nganh { get; set; }
        public string ChuyenNganh { get; set; }
        public string DeThi { get; set; }
        public string BaiLam { get; set; }
        public System.DateTime NgayGioBatDau { get; set; }
        public System.DateTime NgayGioNopBai { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public string LogIP { get; set; }
    }
}
