//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AS_Status_Table_Task
    {
        public System.Guid Id { get; set; }
        public string TableName { get; set; }
        public int Status { get; set; }
        public bool IsSuccess { get; set; }
        public string Message { get; set; }
    }
}
