//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nuce.web.survey.student.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyContext : DbContext
    {
        public SurveyContext()
            : base("name=NUCE_SURVEY_PUBLISHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AS_Academy_Academics> AS_Academy_Academics { get; set; }
        public virtual DbSet<AS_Academy_C_ClassRoom> AS_Academy_C_ClassRoom { get; set; }
        public virtual DbSet<AS_Academy_C_Lecturer_ClassRoom> AS_Academy_C_Lecturer_ClassRoom { get; set; }
        public virtual DbSet<AS_Academy_C_Student_ClassRoom> AS_Academy_C_Student_ClassRoom { get; set; }
        public virtual DbSet<AS_Academy_Class> AS_Academy_Class { get; set; }
        public virtual DbSet<AS_Academy_ClassRoom> AS_Academy_ClassRoom { get; set; }
        public virtual DbSet<AS_Academy_Department> AS_Academy_Department { get; set; }
        public virtual DbSet<AS_Academy_Faculty> AS_Academy_Faculty { get; set; }
        public virtual DbSet<AS_Academy_Lecturer> AS_Academy_Lecturer { get; set; }
        public virtual DbSet<AS_Academy_Lecturer_ClassRoom> AS_Academy_Lecturer_ClassRoom { get; set; }
        public virtual DbSet<AS_Academy_Semester> AS_Academy_Semester { get; set; }
        public virtual DbSet<AS_Academy_Student> AS_Academy_Student { get; set; }
        public virtual DbSet<AS_Academy_Student_ClassRoom> AS_Academy_Student_ClassRoom { get; set; }
        public virtual DbSet<AS_Academy_Subject> AS_Academy_Subject { get; set; }
        public virtual DbSet<AS_Academy_Subject_Extend> AS_Academy_Subject_Extend { get; set; }
        public virtual DbSet<AS_Edu_QA_Week> AS_Edu_QA_Week { get; set; }
        public virtual DbSet<AS_Edu_Survey_BaiKhaoSat> AS_Edu_Survey_BaiKhaoSat { get; set; }
        public virtual DbSet<AS_Edu_Survey_BaiKhaoSat_SinhVien> AS_Edu_Survey_BaiKhaoSat_SinhVien { get; set; }
        public virtual DbSet<AS_Edu_Survey_CauHoi> AS_Edu_Survey_CauHoi { get; set; }
        public virtual DbSet<AS_Edu_Survey_CauTrucDe> AS_Edu_Survey_CauTrucDe { get; set; }
        public virtual DbSet<AS_Edu_Survey_DapAn> AS_Edu_Survey_DapAn { get; set; }
        public virtual DbSet<AS_Edu_Survey_DeThi> AS_Edu_Survey_DeThi { get; set; }
        public virtual DbSet<AS_Edu_Survey_DotKhaoSat> AS_Edu_Survey_DotKhaoSat { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_BaiKhaoSat> AS_Edu_Survey_Graduate_BaiKhaoSat { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_BaiKhaoSat_SinhVien> AS_Edu_Survey_Graduate_BaiKhaoSat_SinhVien { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_CauHoi> AS_Edu_Survey_Graduate_CauHoi { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_CauTrucDe> AS_Edu_Survey_Graduate_CauTrucDe { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_DapAn> AS_Edu_Survey_Graduate_DapAn { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_DeThi> AS_Edu_Survey_Graduate_DeThi { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_Student> AS_Edu_Survey_Graduate_Student { get; set; }
        public virtual DbSet<AS_Edu_Survey_Graduate_SurveyRound> AS_Edu_Survey_Graduate_SurveyRound { get; set; }
        public virtual DbSet<AS_Edu_Survey_ReportTotal> AS_Edu_Survey_ReportTotal { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_BaiKhaoSat> AS_Edu_Survey_Undergraduate_BaiKhaoSat { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien> AS_Edu_Survey_Undergraduate_BaiKhaoSat_SinhVien { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_CauHoi> AS_Edu_Survey_Undergraduate_CauHoi { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_CauTrucDe> AS_Edu_Survey_Undergraduate_CauTrucDe { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_DapAn> AS_Edu_Survey_Undergraduate_DapAn { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_DeThi> AS_Edu_Survey_Undergraduate_DeThi { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_ReportTotal> AS_Edu_Survey_Undergraduate_ReportTotal { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_Student> AS_Edu_Survey_Undergraduate_Student { get; set; }
        public virtual DbSet<AS_Edu_Survey_Undergraduate_SurveyRound> AS_Edu_Survey_Undergraduate_SurveyRound { get; set; }
        public virtual DbSet<AS_Status_Table_Task> AS_Status_Table_Task { get; set; }
    }
}
